trigger:
  - master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

variables:
- group: token
- name: assigned_to
  value: 

stages:
  - stage: preprod
    jobs:
      - job: Add_variables
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                  # Write your commands here
                  # Get the task log ID from the predefined variable
                  taskLogId=$(echo "$(Build.JobId).$(System.StageInstanceId).$(System.JobPositionInStage).21" | tr -d '-')
                  
                  # Construct the URL using the Azure DevOps variables
                  url="https://dev.azure.com/$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs&j=$(taskLogId)"
                  
                  # Print the URL
                  echo "Task Log URL for WhiteSource@21: $url"
          - task: WhiteSource@21
            inputs:
              cwd: '$(System.DefaultWorkingDirectory)'
              projectName: 'a'
          - job: A
            steps:
            - bash: |
                url="$SYSTEM_TEAMFOUNDATIONSERVERURI/$SYSTEM_TEAMPROJECTID/_apis/build/definitions/$(Build.DefinitionVersion)?api-version=7.1-preview.7"
                echo $url
                assigned_to=$(curl -X GET -u:$(System.AccessToken) $url | jq -r '.authoredBy.uniqueName')
                echo $assigned_to
                echo "##vso[task.setvariable variable=myOutputVar;isoutput=true]$assigned_to"
              name: passOutput
            displayName: 'Get User Running the Pipeline'
            outputs:
              - name: myOutputVar
                variable: assigned_to

      - job: B
        dependsOn: A
        variables:
          assigned_to: $[ dependencies.A.outputs['passOutput.myOutputVar'] ]  
        steps:
        - bash: |
            echo "Assigned To: $(assigned_to)"
